// <auto-generated />
using System;
using Azulyoro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Azulyoro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812161645_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Azulyoro.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtId")
                        .HasColumnType("integer")
                        .HasColumnName("ext_id");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("ExtId")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_ext_id");

                    b.ToTable("competitions", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_utc");

                    b.Property<int?>("Elapsed")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed");

                    b.Property<int>("ExtId")
                        .HasColumnType("integer")
                        .HasColumnName("ext_id");

                    b.Property<int?>("FtAway")
                        .HasColumnType("integer")
                        .HasColumnName("ft_away");

                    b.Property<int?>("FtHome")
                        .HasColumnType("integer")
                        .HasColumnName("ft_home");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<int?>("HtAway")
                        .HasColumnType("integer")
                        .HasColumnName("ht_away");

                    b.Property<int?>("HtHome")
                        .HasColumnType("integer")
                        .HasColumnName("ht_home");

                    b.Property<bool>("IsBoca")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boca");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Round")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("round");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue_name");

                    b.HasKey("Id")
                        .HasName("pk_fixtures");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_fixtures_away_team_id");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_fixtures_competition_id");

                    b.HasIndex("DateUtc")
                        .HasDatabaseName("ix_fixtures_date_utc");

                    b.HasIndex("ExtId")
                        .IsUnique()
                        .HasDatabaseName("ix_fixtures_ext_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_fixtures_home_team_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_fixtures_season_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fixtures_status");

                    b.HasIndex("IsBoca", "DateUtc")
                        .HasDatabaseName("ix_fixtures_is_boca_date_utc");

                    b.ToTable("fixtures", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssistPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assist_player_id");

                    b.Property<string>("Comments")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("detail");

                    b.Property<int>("ExtSeq")
                        .HasColumnType("integer")
                        .HasColumnName("ext_seq");

                    b.Property<int?>("ExtraMinute")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minute");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fixture_events");

                    b.HasIndex("FixtureId", "ExtSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_fixture_events_fixture_id_ext_seq");

                    b.ToTable("fixture_events", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoachName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("coach_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Formation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formation");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fixture_lineups");

                    b.HasIndex("FixtureId")
                        .HasDatabaseName("ix_fixture_lineups_fixture_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_fixture_lineups_team_id");

                    b.ToTable("fixture_lineups", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureLineupPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grid")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("grid");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean")
                        .HasColumnName("is_starter");

                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid")
                        .HasColumnName("lineup_id");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fixture_lineup_players");

                    b.HasIndex("LineupId")
                        .HasDatabaseName("ix_fixture_lineup_players_lineup_id");

                    b.ToTable("fixture_lineup_players", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixturePlayerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<int>("Passes")
                        .HasColumnType("integer")
                        .HasColumnName("passes");

                    b.Property<int?>("PassesAccuracy")
                        .HasColumnType("integer")
                        .HasColumnName("passes_accuracy");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rating");

                    b.Property<int>("Red")
                        .HasColumnType("integer")
                        .HasColumnName("red");

                    b.Property<int>("ShotsOn")
                        .HasColumnType("integer")
                        .HasColumnName("shots_on");

                    b.Property<int>("ShotsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("shots_total");

                    b.Property<int>("Tackles")
                        .HasColumnType("integer")
                        .HasColumnName("tackles");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Yellow")
                        .HasColumnType("integer")
                        .HasColumnName("yellow");

                    b.HasKey("Id")
                        .HasName("pk_fixture_player_stats");

                    b.HasIndex("FixtureId", "PlayerId")
                        .HasDatabaseName("ix_fixture_player_stats_fixture_id_player_id");

                    b.ToTable("fixture_player_stats", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtId")
                        .HasColumnType("integer")
                        .HasColumnName("ext_id");

                    b.Property<string>("Firstname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("firstname");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Lastname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nationality");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("position");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("ExtId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_ext_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_players_team_id");

                    b.ToTable("players", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Appearances")
                        .HasColumnType("integer")
                        .HasColumnName("appearances");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rating");

                    b.Property<int>("Red")
                        .HasColumnType("integer")
                        .HasColumnName("red");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Yellow")
                        .HasColumnType("integer")
                        .HasColumnName("yellow");

                    b.HasKey("Id")
                        .HasName("pk_player_season_stats");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_player_season_stats_competition_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_player_season_stats_season_id");

                    b.HasIndex("PlayerId", "CompetitionId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_season_stats_player_id_competition_id_season_id");

                    b.ToTable("player_season_stats", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_year");

                    b.ToTable("seasons", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Draw")
                        .HasColumnType("integer")
                        .HasColumnName("draw");

                    b.Property<string>("Form")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("form");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("integer")
                        .HasColumnName("goals_diff");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer")
                        .HasColumnName("goals_for");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValue("")
                        .HasColumnName("group_name");

                    b.Property<int>("Lose")
                        .HasColumnType("integer")
                        .HasColumnName("lose");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Win")
                        .HasColumnType("integer")
                        .HasColumnName("win");

                    b.HasKey("Id")
                        .HasName("pk_standings");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_standings_season_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_standings_team_id");

                    b.HasIndex("CompetitionId", "SeasonId", "TeamId", "GroupName")
                        .IsUnique()
                        .HasDatabaseName("ix_standings_competition_id_season_id_team_id_group_name");

                    b.ToTable("standings", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastOkAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ok_at");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resource");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sync_states");

                    b.HasIndex("Resource")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_states_resource");

                    b.ToTable("sync_states", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtId")
                        .HasColumnType("integer")
                        .HasColumnName("ext_id");

                    b.Property<int?>("Founded")
                        .HasColumnType("integer")
                        .HasColumnName("founded");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tracked");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("short_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueCity")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("venue_city");

                    b.Property<string>("VenueName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue_name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ExtId")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_ext_id");

                    b.ToTable("teams", "app");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Fixture", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_away_team_id");

                    b.HasOne("Azulyoro.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_competitions_competition_id");

                    b.HasOne("Azulyoro.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_home_team_id");

                    b.HasOne("Azulyoro.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_seasons_season_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureEvent", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Fixture", "Fixture")
                        .WithMany("Events")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_events_fixtures_fixture_id");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureLineup", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Fixture", "Fixture")
                        .WithMany("Lineups")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_lineups_fixtures_fixture_id");

                    b.HasOne("Azulyoro.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_lineups_teams_team_id");

                    b.Navigation("Fixture");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureLineupPlayer", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.FixtureLineup", "Lineup")
                        .WithMany("Players")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_lineup_players_fixture_lineups_lineup_id");

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixturePlayerStats", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Fixture", "Fixture")
                        .WithMany("PlayerStats")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_player_stats_fixtures_fixture_id");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Player", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_players_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_stats_competitions_competition_id");

                    b.HasOne("Azulyoro.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_stats_players_player_id");

                    b.HasOne("Azulyoro.Domain.Entities.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_stats_seasons_season_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Standing", b =>
                {
                    b.HasOne("Azulyoro.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_standings_competitions_competition_id");

                    b.HasOne("Azulyoro.Domain.Entities.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_standings_seasons_season_id");

                    b.HasOne("Azulyoro.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_standings_teams_team_id");

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.Fixture", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lineups");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("Azulyoro.Domain.Entities.FixtureLineup", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
